# This file was generated by GoReleaser. DO NOT EDIT.
cask "tc" do
  name "tc"
  desc "A command-line interface for TeamCity CI/CD server"
  homepage "https://github.com/JetBrains/teamcity-cli"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tc"

  on_macos do
    on_intel do
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v#{version}/tc_#{version}_darwin_x86_64.tar.gz"
      sha256 "0a0c25c5850f6d8e6cf31bb58f8ade689fc0f9c827328aa64342dac4e3989af9"
    end
    on_arm do
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v#{version}/tc_#{version}_darwin_arm64.tar.gz"
      sha256 "e3215c429ca1413e2668f620331adbb78db520ed3ce0d5e576663b5681ce4e76"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v#{version}/tc_#{version}_linux_x86_64.tar.gz"
      sha256 "57d4990eb77a466145578462309dc67a7e8c1debe9f8fa2adc0bd0f2f05def11"
    end
    on_arm do
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v#{version}/tc_#{version}_linux_arm64.tar.gz"
      sha256 "b5dbf7d11beb8b9bdaaf3232c482618082d73f39b8341ee6c8b01217414022b7"
    end
  end

  # No zap stanza required
end
