# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qodana < Formula
  desc "🔧 Run Qodana as fast as possible, with minimum effort required"
  homepage "https://github.com/JetBrains/qodana-cli"
  version "2024.1.6"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/JetBrains/qodana-cli/releases/download/v2024.1.6/qodana_darwin_x86_64.tar.gz"
      sha256 "c2e9bacfb842a3a0890ce81d64d93040dfba996f5cd9df73335ef5448e5c86a6"

      def install
        bin.install "qodana"
      end
    end
    on_arm do
      url "https://github.com/JetBrains/qodana-cli/releases/download/v2024.1.6/qodana_darwin_arm64.tar.gz"
      sha256 "40aa43ab15f3979a7a506dee18eaa7f57cc1c634a8347fd2cf3096750b082b2e"

      def install
        bin.install "qodana"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/JetBrains/qodana-cli/releases/download/v2024.1.6/qodana_linux_x86_64.tar.gz"
        sha256 "6252d97a6e9f674863f3dcc43bb84c48c71db88400c28036738959443591fea4"

        def install
          bin.install "qodana"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/JetBrains/qodana-cli/releases/download/v2024.1.6/qodana_linux_arm64.tar.gz"
        sha256 "8e4f61b30dcebba06923828aef62329acf8f0caa49f2159689dce277c55466bd"

        def install
          bin.install "qodana"
        end
      end
    end
  end
end
