# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qodana < Formula
  desc "🔧 Run Qodana as fast as possible, with minimum effort required"
  homepage "https://github.com/JetBrains/qodana-cli"
  version "2023.2.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/JetBrains/qodana-cli/releases/download/v2023.2.0/qodana_darwin_all.tar.gz"
    sha256 "a00a9ea2a0daec575ffa9f33e19bcbdcab23e88e5d915d00e829e71c2b885e09"

    def install
      bin.install "qodana"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JetBrains/qodana-cli/releases/download/v2023.2.0/qodana_linux_arm64.tar.gz"
      sha256 "04d5cefe10951dc075ccf065d89724d30172318e5c6eeedcfbf1af78e56748bb"

      def install
        bin.install "qodana"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JetBrains/qodana-cli/releases/download/v2023.2.0/qodana_linux_x86_64.tar.gz"
      sha256 "4238660049fc63dda25e0f47208ab3f6ed824ed24fcc809ccd6d5744b8c61d94"

      def install
        bin.install "qodana"
      end
    end
  end
end
