# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qodana < Formula
  desc "🔧 Run Qodana as fast as possible, with minimum effort required"
  homepage "https://github.com/JetBrains/qodana-cli"
  version "2023.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/JetBrains/qodana-cli/releases/download/v2023.1.0/qodana_darwin_arm64.tar.gz"
      sha256 "3912210f45d6b9a2dcb81196b647375e0cdc2988485115da7b66459bc7021f54"

      def install
        bin.install "qodana"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JetBrains/qodana-cli/releases/download/v2023.1.0/qodana_darwin_x86_64.tar.gz"
      sha256 "5f47d3c59fed1ceacd8d3aa85118e78dcd68517d88639c9a005ce10b311e3825"

      def install
        bin.install "qodana"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JetBrains/qodana-cli/releases/download/v2023.1.0/qodana_linux_x86_64.tar.gz"
      sha256 "493de2f6267c22bac0e7d1655b8a0b2ea617fd336534db16e3d5911f4a06d259"

      def install
        bin.install "qodana"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JetBrains/qodana-cli/releases/download/v2023.1.0/qodana_linux_arm64.tar.gz"
      sha256 "fc2aa299a97020e183e608594bbb329498ff355ae1aad1eb10a5670ce5f32c1b"

      def install
        bin.install "qodana"
      end
    end
  end
end
