# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tc < Formula
  desc "A command-line interface for TeamCity CI/CD server"
  homepage "https://github.com/JetBrains/teamcity-cli"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v0.5.0/tc_0.5.0_darwin_x86_64.tar.gz"
      sha256 "6fa27c0c4679adabd790f52db127b5d3699e1f4bc431514b12a5d357987be386"

      def install
        bin.install "tc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v0.5.0/tc_0.5.0_darwin_arm64.tar.gz"
      sha256 "5f80f89e221f60a7477479f87583f9a0b03d21c57b0c15d8784bb3ffd88cc148"

      def install
        bin.install "tc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v0.5.0/tc_0.5.0_linux_x86_64.tar.gz"
      sha256 "8af1d4f7d69bb094c8abfc8e5c5b369e010569a7ee3444c41dba8cc6c57bd09a"
      def install
        bin.install "tc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v0.5.0/tc_0.5.0_linux_arm64.tar.gz"
      sha256 "ec358faa00bd8fc8d53f3648a966d0aa7be2ba1188aa659a953c3a53804cfc23"
      def install
        bin.install "tc"
      end
    end
  end
end
