# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tc < Formula
  desc "A command-line interface for TeamCity CI/CD server"
  homepage "https://github.com/JetBrains/teamcity-cli"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v0.2.0/tc_0.2.0_darwin_x86_64.tar.gz"
      sha256 "e1cea4478c3542a0771a80fd046062e07312c4865d6bf2d1419eefce5bfdbc02"

      def install
        bin.install "tc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v0.2.0/tc_0.2.0_darwin_arm64.tar.gz"
      sha256 "08511c63d3d72fdbcacb810bc6721afe929c03ae9fa1103414e5aa97a522dafb"

      def install
        bin.install "tc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v0.2.0/tc_0.2.0_linux_x86_64.tar.gz"
      sha256 "c915b0a3d43836b68218fe06355c8dd224c1b6c8a4ad44a260cad3a5a92e1fd1"

      def install
        bin.install "tc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v0.2.0/tc_0.2.0_linux_arm64.tar.gz"
      sha256 "6c79b6b6c88b89cb0ee095ffd2a810414c9a79d17aa9dc9c31860d81337ee8c8"

      def install
        bin.install "tc"
      end
    end
  end
end
