# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Teamcity < Formula
  desc "A command-line interface for TeamCity CI/CD server"
  homepage "https://github.com/JetBrains/teamcity-cli"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v1.1.0/teamcity_1.1.0_darwin_x86_64.tar.gz"
      sha256 "374e3dc7b03adc5599774fdf1dcb345b42a1dc96061645f4d26f27a852456be0"

      define_method(:install) do
        bin.install "teamcity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v1.1.0/teamcity_1.1.0_darwin_arm64.tar.gz"
      sha256 "9a4132f77607a65a8450bae1bc3558eabe29073aa6e93f3f12287723247835d4"

      define_method(:install) do
        bin.install "teamcity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v1.1.0/teamcity_1.1.0_linux_x86_64.tar.gz"
      sha256 "d37e4c50d464f867594c6beaecd5d60d5239c24dca1fa59ccc9cdf6a832e3387"
      define_method(:install) do
        bin.install "teamcity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JetBrains/teamcity-cli/releases/download/v1.1.0/teamcity_1.1.0_linux_arm64.tar.gz"
      sha256 "2f661d9f3b3ee2efc6fb48528bd00a61c49a4a50c9ac326c1f9555f7cbb1fab0"
      define_method(:install) do
        bin.install "teamcity"
      end
    end
  end
end
